# Generated by Django 3.0.6 on 2020-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challengefromhighhat'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='reward',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
