# Generated by Django 3.0.6 on 2020-05-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='types',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='usages',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
