# Generated by Django 2.1.3 on 2020-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20200531_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challengefromhighhat',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
